#ifndef TAG_SFIX_H
#define TAG_SFIX_H

typedef enum {
  SFIX_Tag_Protocol_version = 8,
  SFIX_Tag_Body_length = 9,
  SFIX_Tag_Checksum = 10,
  SFIX_Tag_Client_order_id = 11,
  SFIX_Tag_Timestamp = 12,
  SFIX_Tag_list_length = 20,
  SFIX_Tag_List = 21,
  SFIX_Tag_Message_type = 35,
  SFIX_Tag_Quantity = 38,
  SFIX_Tag_Price = 44,
  SFIX_Tag_Order_type = 45,
  SFIX_Tag_Order_status = 46,
  SFIX_Tag_Sender_comp_id = 49,
  SFIX_Tag_Side = 54,
  SFIX_Tag_Symbol = 55,
  SFIX_Tag_Target_comp_id = 56,
  SFIX_Tag_Time_in_force = 59,
  SFIX_Tag_Transaction_time = 60,
  SFIX_Tag_Date = 61,
  SFIX_Tag_Time = 62,
  SFIX_Tag_Open = 63,
  SFIX_Tag_High = 64,
  SFIX_Tag_Low = 65,
  SFIX_Tag_Close = 66,
  SFIX_Tag_Up_volume = 67,
  SFIX_Tag_Down_volume = 69,
  SFIX_Tag_Total_volume = 70,
  SFIX_Tag_Up_ticks = 71,
  SFIX_Tag_Down_ticks = 72,
  SFIX_Tag_Total_ticks = 73,
  SFIX_Tag_Capital = 74,
  SFIX_Tag_Market_position = 75,
  SFIX_Tag_Equity = 76,
  SFIX_Tag_Last_price = 77,
  SFIX_Tag_Strategy = 78,
  SFIX_Tag_Spread = 79,
  SFIX_Tag_Number_of_trades = 80,
  SFIX_Tag_Broker_commision_dpm = 81,
} SFIX_Tag;

#endif
